### ISSUE TITLE
Last line(s) of output disappear while in shell mode

### ISSUE THREAD

**Issue by CoRoGi** [bakks/butterfish#8]
When running butterfish in shell mode, the responses I receive back will lose their last line or two once the command prompt is returned.

**Comment by bakks** [comment]
Hey @CoRoGi - can you tell me what terminal and shell you're using? And what your `PS1` (terminal prompt) looks like? I haven't seen this bug so I suspect it's some setup I haven't tried.

**Comment by CoRoGi** [comment]
Hi, yes i'm using iTerm2 with zsh, with essentially an oh-my-zsh set up. Here's a picture:

<img width="1397" alt="Screenshot 2023-05-15 at 6 42 43 PM" src="https://github.com/bakks/butterfish/assets/123400756/f7864176-dfa0-4260-9bf0-8c6b333cfbf1">

**Comment by bakks** [comment]
Ahhh - so the issue is that the shell mode code is currently assuming a 1 line command prompt, that's why it's erasing the last few lines. Workaround is to change your `PS1` to something simpler (e.g. `export PS1='> '`).

I want to support this though, I'm separately reworking how the prompt is handled so it will be a few days but should be able to make it work. Will respond back once it's working.

**Comment by CoRoGi** [comment]
Ah yes that certainly explains it, thank you! In case anyone else runs into this: I ended up updating my zshrc's ZSH_THEME variable to be a one line prompt (gallifrey in this case) instead of powerlevel10k and then sourced it + ran exec zsh to resolve this issue. Shell mode now displays its text just fine. Looking forward to the updates on supporting multiline command prompt!

**Comment by bakks** [comment]
Ok @CoRoGi I did some more testing. My new conclusion - the issue here isn't the fact that the prompt was multiple lines, it was a zsh(?) feature called "Transient Prompt" that [Powerlevel10k makes it easy to turn on](https://github.com/romkatv/powerlevel10k/#transient-prompt). You likely flipped this on when configuring p10k.

The p10k behavior is that it uses transient prompting to print the `~......` line in your example, but then erases that line and later places it below so that your history looks a lot cleaner. Basically zsh/p10k is mucking with the terminal output in a way that's incompatible with Butterfish, and I don't see a good way to make it compatible.

So the upshot here is: you can still use p10k with Butterfish, just don't turn on the Transient Prompt feature! I hope this helps, let me know if I've misinterpreted this.
